# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Install Playwright
      run: npx playwright install

    - name: Run Application
      run: npm run start &

    - name: Sleep Thread
      run: npm sleep 5

    - name: Run Unit Tests
      run: npm run test:unit

    - name: Run UI Tests
      run: npm run test:ui

    - name: Output SoftUni Username
      run: echo alexanderstoyanov123
    
